package prepare.datastructures.arrays._5_sparse_arrays;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class SolutionTest {

    @Test
    public void testSolution() {
        List<AbstractSolution> solutions = List.of(
                new ManualHashMap(),
                new AutoHashMap(),
                new BubbleLoL()
        );

        for (AbstractSolution s : solutions) {
            assertEquals(output9(), s.matchingStrings(input9_1(), input9_2()));
            assertEquals(List.of(2, 1, 0), s.matchingStrings(input10_1(), input10_2()));
            assertEquals(List.of(1, 0, 1), s.matchingStrings(input11_1(), input11_2()));
            assertEquals(List.of(1, 3, 4, 3, 2), s.matchingStrings(input12_1(), input12_2()));
        }
    }

    List<String> input9_1() {
        List<String> r = new ArrayList<>(980);
        r.add("yktkqhusnsbh");
        r.add("rzdgauiaqfd");
        r.add("qkhwynrlneksncv");
        r.add("fkgoemvsvg");
        r.add("eyrphlbrkw");
        r.add("mhakcihhthaajuamlg");
        r.add("hcbgcccvxs");
        r.add("outizmnucqkxdlfyxqg");
        r.add("palaxwkqxstdah");
        r.add("zktdtizkrcljederuxs");
        r.add("hvagmzgwgjmztncde");
        r.add("maenrdysbritmbtvyy");
        r.add("qacecpatcxoibelsaad");
        r.add("kbrkcxtvemurk");
        r.add("pcdvbycynxymmrajlh");
        r.add("vxkbsfyvywp");
        r.add("gpuvekxdscnfdferoax");
        r.add("ltlfgqpkuaw");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("vnwwgxpvmnqev");
        r.add("xtujyxukoywdwu");
        r.add("rbydiynhywxgdfado");
        r.add("ghasjwxzvqjyiem");
        r.add("qmrsqbaatfzu");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("veozzplakcamuplgpx");
        r.add("veozzplakcamuplgpx");
        r.add("azxxwcjitbkfkxabxv");
        r.add("cnzvvbicdocbfzcvg");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("eaugxiwfddefirhcf");
        r.add("outizmnucqkxdlfyxqg");
        r.add("xungqrwaihorcwb");
        r.add("jsycwwqxrmpogurhbs");
        r.add("aizbsegmkcehkv");
        r.add("mhakcihhthaajuamlg");
        r.add("sjonqszwcwktxw");
        r.add("xfsjxooclcycwcn");
        r.add("cgxllhichirichbzma");
        r.add("cvyebywhzrheav");
        r.add("fswnwcgwwzazfbw");
        r.add("lywaxsogirghqgj");
        r.add("hlloonkdmanq");
        r.add("bjbedtpdcgcilwl");
        r.add("hqsdgjtpfxwzx");
        r.add("palaxwkqxstdah");
        r.add("uuqokimbilegfjrhzu");
        r.add("zfoofhbffi");
        r.add("llpntyizbeb");
        r.add("cnzvvbicdocbfzcvg");
        r.add("rbydiynhywxgdfado");
        r.add("pinxwmmeifueviczi");
        r.add("pcdvbycynxymmrajlh");
        r.add("tbsxdnjmagnpz");
        r.add("vgjxxhosif");
        r.add("ghasjwxzvqjyiem");
        r.add("vvufjbgdpvfy");
        r.add("llpntyizbeb");
        r.add("vgjxxhosif");
        r.add("bjbedtpdcgcilwl");
        r.add("hvagmzgwgjmztncde");
        r.add("hjnirpgylrvicvn");
        r.add("sjonqszwcwktxw");
        r.add("qacecpatcxoibelsaad");
        r.add("pcdvbycynxymmrajlh");
        r.add("dzstfixtnfccvwd");
        r.add("iglexamfdtvt");
        r.add("mhakcihhthaajuamlg");
        r.add("npjksoupvwuuklv");
        r.add("palaxwkqxstdah");
        r.add("pcdvbycynxymmrajlh");
        r.add("ghasjwxzvqjyiem");
        r.add("xfsjxooclcycwcn");
        r.add("uuqokimbilegfjrhzu");
        r.add("biviykdljlegtlimzil");
        r.add("zxyqmmiqnjnpg");
        r.add("sfduuipjzhhkvtiv");
        r.add("palaxwkqxstdah");
        r.add("kowvhbqhmthb");
        r.add("zfoofhbffi");
        r.add("sfduuipjzhhkvtiv");
        r.add("pinxwmmeifueviczi");
        r.add("mhakcihhthaajuamlg");
        r.add("aizbsegmkcehkv");
        r.add("xujqjgidmzuilic");
        r.add("iysxcgoufz");
        r.add("nitcfysgzvbcz");
        r.add("kbrkcxtvemurk");
        r.add("cvyebywhzrheav");
        r.add("hvagmzgwgjmztncde");
        r.add("hvagmzgwgjmztncde");
        r.add("qfvwoqfsoidz");
        r.add("vgjxxhosif");
        r.add("xfsjxooclcycwcn");
        r.add("dzstfixtnfccvwd");
        r.add("zktdtizkrcljederuxs");
        r.add("cvyebywhzrheav");
        r.add("hcbgcccvxs");
        r.add("bkclrgwnzmbut");
        r.add("xzscqzxmcejqjq");
        r.add("dvlahbxlvr");
        r.add("jsycwwqxrmpogurhbs");
        r.add("bypmwgpbgmsujnlowj");
        r.add("nddrscobfrojtwew");
        r.add("cnzvvbicdocbfzcvg");
        r.add("pinxwmmeifueviczi");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("thzrjtjpousq");
        r.add("vpkytxfbeaqcioe");
        r.add("ejfeswctcdbrfnqy");
        r.add("pawsrhagbgzlsv");
        r.add("jsycwwqxrmpogurhbs");
        r.add("sgdpknswxysln");
        r.add("palaxwkqxstdah");
        r.add("sgdpknswxysln");
        r.add("ghasjwxzvqjyiem");
        r.add("hjnirpgylrvicvn");
        r.add("azxxwcjitbkfkxabxv");
        r.add("bkclrgwnzmbut");
        r.add("yjhejabudyfipd");
        r.add("ltlfgqpkuaw");
        r.add("aizbsegmkcehkv");
        r.add("palaxwkqxstdah");
        r.add("cvyebywhzrheav");
        r.add("skthxigeyrye");
        r.add("kbrkcxtvemurk");
        r.add("xfsjxooclcycwcn");
        r.add("vswlswwjpooelqttk");
        r.add("ltlfgqpkuaw");
        r.add("azxxwcjitbkfkxabxv");
        r.add("vfvvmfxhyenhzz");
        r.add("uuqokimbilegfjrhzu");
        r.add("jsycwwqxrmpogurhbs");
        r.add("vgjxxhosif");
        r.add("vxkbsfyvywp");
        r.add("hqsdgjtpfxwzx");
        r.add("zfoofhbffi");
        r.add("vpkytxfbeaqcioe");
        r.add("dvlahbxlvr");
        r.add("bypmwgpbgmsujnlowj");
        r.add("pinxwmmeifueviczi");
        r.add("hqsdgjtpfxwzx");
        r.add("hlloonkdmanq");
        r.add("iufqqsymxpsopnwuyh");
        r.add("xfsjxooclcycwcn");
        r.add("iufqqsymxpsopnwuyh");
        r.add("yjhejabudyfipd");
        r.add("npjksoupvwuuklv");
        r.add("tqfqorsmvuolskkvfj");
        r.add("xungqrwaihorcwb");
        r.add("wrxouegcmsfbhb");
        r.add("shrnzqokjsmtkcc");
        r.add("vswlswwjpooelqttk");
        r.add("xujqjgidmzuilic");
        r.add("cgxllhichirichbzma");
        r.add("tbsxdnjmagnpz");
        r.add("vpkytxfbeaqcioe");
        r.add("zrovgoudbnwrougxqz");
        r.add("qacecpatcxoibelsaad");
        r.add("bkclrgwnzmbut");
        r.add("hrwroqumokjcb");
        r.add("qkhwynrlneksncv");
        r.add("cmhggogvznkvwon");
        r.add("kbrkcxtvemurk");
        r.add("fkgoemvsvg");
        r.add("vnwwgxpvmnqev");
        r.add("bypmwgpbgmsujnlowj");
        r.add("skthxigeyrye");
        r.add("cmhggogvznkvwon");
        r.add("rzdgauiaqfd");
        r.add("sgdpknswxysln");
        r.add("pawsrhagbgzlsv");
        r.add("dgysbzweva");
        r.add("skthxigeyrye");
        r.add("skthxigeyrye");
        r.add("vgjxxhosif");
        r.add("vgjxxhosif");
        r.add("lywaxsogirghqgj");
        r.add("vvufjbgdpvfy");
        r.add("aizbsegmkcehkv");
        r.add("lfdfiuwfrnevaraz");
        r.add("iufqqsymxpsopnwuyh");
        r.add("yktkqhusnsbh");
        r.add("vpkytxfbeaqcioe");
        r.add("nddrscobfrojtwew");
        r.add("vvufjbgdpvfy");
        r.add("outizmnucqkxdlfyxqg");
        r.add("yjhejabudyfipd");
        r.add("vgjxxhosif");
        r.add("gdswuqisedicz");
        r.add("cnzvvbicdocbfzcvg");
        r.add("jsycwwqxrmpogurhbs");
        r.add("wrxouegcmsfbhb");
        r.add("uuqokimbilegfjrhzu");
        r.add("xujqjgidmzuilic");
        r.add("ltlfgqpkuaw");
        r.add("vnwwgxpvmnqev");
        r.add("fkgoemvsvg");
        r.add("xfsjxooclcycwcn");
        r.add("kowvhbqhmthb");
        r.add("gdswuqisedicz");
        r.add("uuqokimbilegfjrhzu");
        r.add("tbsxdnjmagnpz");
        r.add("veozzplakcamuplgpx");
        r.add("bypmwgpbgmsujnlowj");
        r.add("iufqqsymxpsopnwuyh");
        r.add("kbrkcxtvemurk");
        r.add("wrxouegcmsfbhb");
        r.add("vnwwgxpvmnqev");
        r.add("kowvhbqhmthb");
        r.add("tbsxdnjmagnpz");
        r.add("eyrphlbrkw");
        r.add("cgxllhichirichbzma");
        r.add("xujqjgidmzuilic");
        r.add("eyrphlbrkw");
        r.add("mhakcihhthaajuamlg");
        r.add("iufqqsymxpsopnwuyh");
        r.add("veozzplakcamuplgpx");
        r.add("lywaxsogirghqgj");
        r.add("lfdfiuwfrnevaraz");
        r.add("qfvwoqfsoidz");
        r.add("xujqjgidmzuilic");
        r.add("tbsxdnjmagnpz");
        r.add("cnzvvbicdocbfzcvg");
        r.add("pinxwmmeifueviczi");
        r.add("qacecpatcxoibelsaad");
        r.add("zktdtizkrcljederuxs");
        r.add("hqsdgjtpfxwzx");
        r.add("yktkqhusnsbh");
        r.add("ghasjwxzvqjyiem");
        r.add("fswnwcgwwzazfbw");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("kowvhbqhmthb");
        r.add("kyqhtekrdfcigv");
        r.add("qfvwoqfsoidz");
        r.add("xtujyxukoywdwu");
        r.add("pinxwmmeifueviczi");
        r.add("bjbedtpdcgcilwl");
        r.add("zrovgoudbnwrougxqz");
        r.add("zfoofhbffi");
        r.add("cvyebywhzrheav");
        r.add("xzscqzxmcejqjq");
        r.add("fswnwcgwwzazfbw");
        r.add("eyrphlbrkw");
        r.add("wrxouegcmsfbhb");
        r.add("yjhejabudyfipd");
        r.add("rlmeprpzlifivjpdf");
        r.add("eyrphlbrkw");
        r.add("outizmnucqkxdlfyxqg");
        r.add("bypmwgpbgmsujnlowj");
        r.add("shrnzqokjsmtkcc");
        r.add("mhakcihhthaajuamlg");
        r.add("hcbgcccvxs");
        r.add("hvagmzgwgjmztncde");
        r.add("npjksoupvwuuklv");
        r.add("iysxcgoufz");
        r.add("vswlswwjpooelqttk");
        r.add("npjksoupvwuuklv");
        r.add("tbsxdnjmagnpz");
        r.add("npjksoupvwuuklv");
        r.add("dvlahbxlvr");
        r.add("zxyqmmiqnjnpg");
        r.add("vfvvmfxhyenhzz");
        r.add("qfvwoqfsoidz");
        r.add("biviykdljlegtlimzil");
        r.add("gfzkakdfwvflslyohzi");
        r.add("cmhggogvznkvwon");
        r.add("yktkqhusnsbh");
        r.add("eyrphlbrkw");
        r.add("llpntyizbeb");
        r.add("vgjxxhosif");
        r.add("shrnzqokjsmtkcc");
        r.add("ylwwujbuoxzxr");
        r.add("mobwckzanokv");
        r.add("kowvhbqhmthb");
        r.add("rzdgauiaqfd");
        r.add("vxkbsfyvywp");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("outizmnucqkxdlfyxqg");
        r.add("elgnstionj");
        r.add("palaxwkqxstdah");
        r.add("nddrscobfrojtwew");
        r.add("shrnzqokjsmtkcc");
        r.add("vvufjbgdpvfy");
        r.add("sfduuipjzhhkvtiv");
        r.add("vswlswwjpooelqttk");
        r.add("dgysbzweva");
        r.add("hqsdgjtpfxwzx");
        r.add("vgjxxhosif");
        r.add("vfvvmfxhyenhzz");
        r.add("uhyatwgdcnwcxoas");
        r.add("llpntyizbeb");
        r.add("qmrsqbaatfzu");
        r.add("bkclrgwnzmbut");
        r.add("dvlahbxlvr");
        r.add("vswlswwjpooelqttk");
        r.add("rsffaewcsxxocl");
        r.add("hlloonkdmanq");
        r.add("veozzplakcamuplgpx");
        r.add("vxkbsfyvywp");
        r.add("qkhwynrlneksncv");
        r.add("mobwckzanokv");
        r.add("ghasjwxzvqjyiem");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("biviykdljlegtlimzil");
        r.add("aizbsegmkcehkv");
        r.add("pinxwmmeifueviczi");
        r.add("sjonqszwcwktxw");
        r.add("kbrkcxtvemurk");
        r.add("xfsjxooclcycwcn");
        r.add("outizmnucqkxdlfyxqg");
        r.add("lywaxsogirghqgj");
        r.add("vfvvmfxhyenhzz");
        r.add("iglexamfdtvt");
        r.add("fkgoemvsvg");
        r.add("zfoofhbffi");
        r.add("palaxwkqxstdah");
        r.add("nitcfysgzvbcz");
        r.add("cmhggogvznkvwon");
        r.add("ejfeswctcdbrfnqy");
        r.add("sfduuipjzhhkvtiv");
        r.add("hlloonkdmanq");
        r.add("dgysbzweva");
        r.add("hlloonkdmanq");
        r.add("ghasjwxzvqjyiem");
        r.add("bjbedtpdcgcilwl");
        r.add("crexopedtp");
        r.add("iglexamfdtvt");
        r.add("gfzkakdfwvflslyohzi");
        r.add("bjbedtpdcgcilwl");
        r.add("uhyatwgdcnwcxoas");
        r.add("iysxcgoufz");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("fkgoemvsvg");
        r.add("xtujyxukoywdwu");
        r.add("llpntyizbeb");
        r.add("xujqjgidmzuilic");
        r.add("vvufjbgdpvfy");
        r.add("gikbbcuucfceho");
        r.add("vxkbsfyvywp");
        r.add("npjksoupvwuuklv");
        r.add("nddrscobfrojtwew");
        r.add("gfzkakdfwvflslyohzi");
        r.add("gdswuqisedicz");
        r.add("ltlfgqpkuaw");
        r.add("sfduuipjzhhkvtiv");
        r.add("ltlfgqpkuaw");
        r.add("hlloonkdmanq");
        r.add("crexopedtp");
        r.add("pawsrhagbgzlsv");
        r.add("gpuvekxdscnfdferoax");
        r.add("vvufjbgdpvfy");
        r.add("rlmeprpzlifivjpdf");
        r.add("qfvwoqfsoidz");
        r.add("qkhwynrlneksncv");
        r.add("iysxcgoufz");
        r.add("kyqhtekrdfcigv");
        r.add("zfoofhbffi");
        r.add("zfoofhbffi");
        r.add("gikbbcuucfceho");
        r.add("vpkytxfbeaqcioe");
        r.add("mhakcihhthaajuamlg");
        r.add("npjksoupvwuuklv");
        r.add("cvyebywhzrheav");
        r.add("mhakcihhthaajuamlg");
        r.add("vvufjbgdpvfy");
        r.add("bjbedtpdcgcilwl");
        r.add("rbydiynhywxgdfado");
        r.add("sjonqszwcwktxw");
        r.add("xfsjxooclcycwcn");
        r.add("ejfeswctcdbrfnqy");
        r.add("azxxwcjitbkfkxabxv");
        r.add("rbydiynhywxgdfado");
        r.add("veozzplakcamuplgpx");
        r.add("shrnzqokjsmtkcc");
        r.add("ylwwujbuoxzxr");
        r.add("qfvwoqfsoidz");
        r.add("lcwvndudzxxoxzgti");
        r.add("aizbsegmkcehkv");
        r.add("shrnzqokjsmtkcc");
        r.add("elgnstionj");
        r.add("iglexamfdtvt");
        r.add("biviykdljlegtlimzil");
        r.add("maenrdysbritmbtvyy");
        r.add("cnzvvbicdocbfzcvg");
        r.add("rsffaewcsxxocl");
        r.add("vvufjbgdpvfy");
        r.add("eaugxiwfddefirhcf");
        r.add("lcwvndudzxxoxzgti");
        r.add("zrovgoudbnwrougxqz");
        r.add("bypmwgpbgmsujnlowj");
        r.add("kbrkcxtvemurk");
        r.add("qkhwynrlneksncv");
        r.add("ltlfgqpkuaw");
        r.add("llpntyizbeb");
        r.add("dgysbzweva");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("vnwwgxpvmnqev");
        r.add("lcwvndudzxxoxzgti");
        r.add("hrwroqumokjcb");
        r.add("outizmnucqkxdlfyxqg");
        r.add("dvlahbxlvr");
        r.add("hrwroqumokjcb");
        r.add("qacecpatcxoibelsaad");
        r.add("zktdtizkrcljederuxs");
        r.add("yjhejabudyfipd");
        r.add("bypmwgpbgmsujnlowj");
        r.add("shrnzqokjsmtkcc");
        r.add("cvyebywhzrheav");
        r.add("uuqokimbilegfjrhzu");
        r.add("hqsdgjtpfxwzx");
        r.add("yjhejabudyfipd");
        r.add("ylwwujbuoxzxr");
        r.add("biviykdljlegtlimzil");
        r.add("hcbgcccvxs");
        r.add("hqsdgjtpfxwzx");
        r.add("rlmeprpzlifivjpdf");
        r.add("dzstfixtnfccvwd");
        r.add("tqfqorsmvuolskkvfj");
        r.add("jsycwwqxrmpogurhbs");
        r.add("vnwwgxpvmnqev");
        r.add("zktdtizkrcljederuxs");
        r.add("gikbbcuucfceho");
        r.add("dgysbzweva");
        r.add("cnzvvbicdocbfzcvg");
        r.add("hlloonkdmanq");
        r.add("ejfeswctcdbrfnqy");
        r.add("cnzvvbicdocbfzcvg");
        r.add("vpkytxfbeaqcioe");
        r.add("hqsdgjtpfxwzx");
        r.add("elgnstionj");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("xtujyxukoywdwu");
        r.add("rzdgauiaqfd");
        r.add("uhyatwgdcnwcxoas");
        r.add("lcwvndudzxxoxzgti");
        r.add("qmrsqbaatfzu");
        r.add("vpkytxfbeaqcioe");
        r.add("eyrphlbrkw");
        r.add("dvlahbxlvr");
        r.add("ejfeswctcdbrfnqy");
        r.add("yktkqhusnsbh");
        r.add("gdswuqisedicz");
        r.add("jsycwwqxrmpogurhbs");
        r.add("eyrphlbrkw");
        r.add("iufqqsymxpsopnwuyh");
        r.add("hjnirpgylrvicvn");
        r.add("eyrphlbrkw");
        r.add("azxxwcjitbkfkxabxv");
        r.add("iglexamfdtvt");
        r.add("biviykdljlegtlimzil");
        r.add("nddrscobfrojtwew");
        r.add("ghasjwxzvqjyiem");
        r.add("lfdfiuwfrnevaraz");
        r.add("eaugxiwfddefirhcf");
        r.add("cgxllhichirichbzma");
        r.add("zfoofhbffi");
        r.add("bkclrgwnzmbut");
        r.add("zrovgoudbnwrougxqz");
        r.add("kowvhbqhmthb");
        r.add("hcbgcccvxs");
        r.add("uuqokimbilegfjrhzu");
        r.add("bypmwgpbgmsujnlowj");
        r.add("hjnirpgylrvicvn");
        r.add("vpkytxfbeaqcioe");
        r.add("veozzplakcamuplgpx");
        r.add("dvlahbxlvr");
        r.add("xfsjxooclcycwcn");
        r.add("eyrphlbrkw");
        r.add("gdswuqisedicz");
        r.add("eyrphlbrkw");
        r.add("ejfeswctcdbrfnqy");
        r.add("vpkytxfbeaqcioe");
        r.add("vfvvmfxhyenhzz");
        r.add("cmhggogvznkvwon");
        r.add("yktkqhusnsbh");
        r.add("eaugxiwfddefirhcf");
        r.add("kyqhtekrdfcigv");
        r.add("nitcfysgzvbcz");
        r.add("rlmeprpzlifivjpdf");
        r.add("vswlswwjpooelqttk");
        r.add("hrwroqumokjcb");
        r.add("hlloonkdmanq");
        r.add("kyqhtekrdfcigv");
        r.add("qmrsqbaatfzu");
        r.add("qacecpatcxoibelsaad");
        r.add("mhakcihhthaajuamlg");
        r.add("tqfqorsmvuolskkvfj");
        r.add("mhakcihhthaajuamlg");
        r.add("palaxwkqxstdah");
        r.add("dvlahbxlvr");
        r.add("xzscqzxmcejqjq");
        r.add("cgxllhichirichbzma");
        r.add("biviykdljlegtlimzil");
        r.add("wrxouegcmsfbhb");
        r.add("jsycwwqxrmpogurhbs");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("cvyebywhzrheav");
        r.add("qfvwoqfsoidz");
        r.add("veozzplakcamuplgpx");
        r.add("ghasjwxzvqjyiem");
        r.add("pawsrhagbgzlsv");
        r.add("lfdfiuwfrnevaraz");
        r.add("crexopedtp");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("maenrdysbritmbtvyy");
        r.add("dvlahbxlvr");
        r.add("fswnwcgwwzazfbw");
        r.add("wgrpqtrvgixjpajoin");
        r.add("iglexamfdtvt");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("sfduuipjzhhkvtiv");
        r.add("pawsrhagbgzlsv");
        r.add("tqfqorsmvuolskkvfj");
        r.add("uuqokimbilegfjrhzu");
        r.add("bjbedtpdcgcilwl");
        r.add("hqsdgjtpfxwzx");
        r.add("zktdtizkrcljederuxs");
        r.add("skthxigeyrye");
        r.add("zrovgoudbnwrougxqz");
        r.add("npjksoupvwuuklv");
        r.add("maenrdysbritmbtvyy");
        r.add("zrovgoudbnwrougxqz");
        r.add("jsycwwqxrmpogurhbs");
        r.add("maenrdysbritmbtvyy");
        r.add("cmhggogvznkvwon");
        r.add("dgysbzweva");
        r.add("thzrjtjpousq");
        r.add("zfoofhbffi");
        r.add("qkhwynrlneksncv");
        r.add("qfvwoqfsoidz");
        r.add("lywaxsogirghqgj");
        r.add("xungqrwaihorcwb");
        r.add("hqsdgjtpfxwzx");
        r.add("hjnirpgylrvicvn");
        r.add("mhakcihhthaajuamlg");
        r.add("hjnirpgylrvicvn");
        r.add("sgdpknswxysln");
        r.add("qkhwynrlneksncv");
        r.add("nddrscobfrojtwew");
        r.add("jsycwwqxrmpogurhbs");
        r.add("lcwvndudzxxoxzgti");
        r.add("yjhejabudyfipd");
        r.add("lcwvndudzxxoxzgti");
        r.add("fkgoemvsvg");
        r.add("wrxouegcmsfbhb");
        r.add("mobwckzanokv");
        r.add("qmrsqbaatfzu");
        r.add("nitcfysgzvbcz");
        r.add("xfsjxooclcycwcn");
        r.add("elgnstionj");
        r.add("cgxllhichirichbzma");
        r.add("uhyatwgdcnwcxoas");
        r.add("nitcfysgzvbcz");
        r.add("eaugxiwfddefirhcf");
        r.add("kyqhtekrdfcigv");
        r.add("vxkbsfyvywp");
        r.add("crexopedtp");
        r.add("lcwvndudzxxoxzgti");
        r.add("yjhejabudyfipd");
        r.add("rlmeprpzlifivjpdf");
        r.add("tqfqorsmvuolskkvfj");
        r.add("cmhggogvznkvwon");
        r.add("qmrsqbaatfzu");
        r.add("gdswuqisedicz");
        r.add("rbydiynhywxgdfado");
        r.add("elgnstionj");
        r.add("qfvwoqfsoidz");
        r.add("cnzvvbicdocbfzcvg");
        r.add("gpuvekxdscnfdferoax");
        r.add("lfdfiuwfrnevaraz");
        r.add("dzstfixtnfccvwd");
        r.add("yjhejabudyfipd");
        r.add("aizbsegmkcehkv");
        r.add("iufqqsymxpsopnwuyh");
        r.add("dvlahbxlvr");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("dvlahbxlvr");
        r.add("npjksoupvwuuklv");
        r.add("hvagmzgwgjmztncde");
        r.add("ghasjwxzvqjyiem");
        r.add("xtujyxukoywdwu");
        r.add("maenrdysbritmbtvyy");
        r.add("dgysbzweva");
        r.add("vgjxxhosif");
        r.add("hlloonkdmanq");
        r.add("zfoofhbffi");
        r.add("yjhejabudyfipd");
        r.add("thzrjtjpousq");
        r.add("kowvhbqhmthb");
        r.add("llpntyizbeb");
        r.add("outizmnucqkxdlfyxqg");
        r.add("vvufjbgdpvfy");
        r.add("shrnzqokjsmtkcc");
        r.add("sgdpknswxysln");
        r.add("cvyebywhzrheav");
        r.add("zfoofhbffi");
        r.add("vpkytxfbeaqcioe");
        r.add("iglexamfdtvt");
        r.add("yktkqhusnsbh");
        r.add("pinxwmmeifueviczi");
        r.add("ltlfgqpkuaw");
        r.add("jsycwwqxrmpogurhbs");
        r.add("sfduuipjzhhkvtiv");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("hqsdgjtpfxwzx");
        r.add("vgjxxhosif");
        r.add("veozzplakcamuplgpx");
        r.add("outizmnucqkxdlfyxqg");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("gfzkakdfwvflslyohzi");
        r.add("pawsrhagbgzlsv");
        r.add("pcdvbycynxymmrajlh");
        r.add("zxyqmmiqnjnpg");
        r.add("vpkytxfbeaqcioe");
        r.add("vxkbsfyvywp");
        r.add("kbrkcxtvemurk");
        r.add("pcdvbycynxymmrajlh");
        r.add("eyrphlbrkw");
        r.add("wrxouegcmsfbhb");
        r.add("kowvhbqhmthb");
        r.add("hlloonkdmanq");
        r.add("eyrphlbrkw");
        r.add("kbrkcxtvemurk");
        r.add("npjksoupvwuuklv");
        r.add("nitcfysgzvbcz");
        r.add("iysxcgoufz");
        r.add("dgysbzweva");
        r.add("skthxigeyrye");
        r.add("cvyebywhzrheav");
        r.add("zfoofhbffi");
        r.add("yktkqhusnsbh");
        r.add("uuqokimbilegfjrhzu");
        r.add("vfvvmfxhyenhzz");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("zrovgoudbnwrougxqz");
        r.add("ghasjwxzvqjyiem");
        r.add("lywaxsogirghqgj");
        r.add("vfvvmfxhyenhzz");
        r.add("gpuvekxdscnfdferoax");
        r.add("pinxwmmeifueviczi");
        r.add("rsffaewcsxxocl");
        r.add("lywaxsogirghqgj");
        r.add("dgysbzweva");
        r.add("eaugxiwfddefirhcf");
        r.add("llpntyizbeb");
        r.add("cgxllhichirichbzma");
        r.add("eaugxiwfddefirhcf");
        r.add("uuqokimbilegfjrhzu");
        r.add("dzstfixtnfccvwd");
        r.add("vxkbsfyvywp");
        r.add("skthxigeyrye");
        r.add("sgdpknswxysln");
        r.add("llpntyizbeb");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("xzscqzxmcejqjq");
        r.add("uhyatwgdcnwcxoas");
        r.add("eaugxiwfddefirhcf");
        r.add("vvufjbgdpvfy");
        r.add("dvlahbxlvr");
        r.add("jsycwwqxrmpogurhbs");
        r.add("vswlswwjpooelqttk");
        r.add("fswnwcgwwzazfbw");
        r.add("hjnirpgylrvicvn");
        r.add("vswlswwjpooelqttk");
        r.add("mobwckzanokv");
        r.add("vgjxxhosif");
        r.add("sfduuipjzhhkvtiv");
        r.add("sgdpknswxysln");
        r.add("kbrkcxtvemurk");
        r.add("mobwckzanokv");
        r.add("veozzplakcamuplgpx");
        r.add("veozzplakcamuplgpx");
        r.add("outizmnucqkxdlfyxqg");
        r.add("yktkqhusnsbh");
        r.add("lywaxsogirghqgj");
        r.add("hvagmzgwgjmztncde");
        r.add("vxkbsfyvywp");
        r.add("bypmwgpbgmsujnlowj");
        r.add("iysxcgoufz");
        r.add("xzscqzxmcejqjq");
        r.add("eyrphlbrkw");
        r.add("iglexamfdtvt");
        r.add("cgxllhichirichbzma");
        r.add("iglexamfdtvt");
        r.add("cvyebywhzrheav");
        r.add("eaugxiwfddefirhcf");
        r.add("shrnzqokjsmtkcc");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("lfdfiuwfrnevaraz");
        r.add("veozzplakcamuplgpx");
        r.add("gpuvekxdscnfdferoax");
        r.add("mhakcihhthaajuamlg");
        r.add("npjksoupvwuuklv");
        r.add("thzrjtjpousq");
        r.add("cnzvvbicdocbfzcvg");
        r.add("tbsxdnjmagnpz");
        r.add("maenrdysbritmbtvyy");
        r.add("zfoofhbffi");
        r.add("gfzkakdfwvflslyohzi");
        r.add("hlloonkdmanq");
        r.add("mhakcihhthaajuamlg");
        r.add("vxkbsfyvywp");
        r.add("biviykdljlegtlimzil");
        r.add("vnwwgxpvmnqev");
        r.add("qkhwynrlneksncv");
        r.add("ghasjwxzvqjyiem");
        r.add("wrxouegcmsfbhb");
        r.add("fkgoemvsvg");
        r.add("sfduuipjzhhkvtiv");
        r.add("iglexamfdtvt");
        r.add("llpntyizbeb");
        r.add("sjonqszwcwktxw");
        r.add("xujqjgidmzuilic");
        r.add("xungqrwaihorcwb");
        r.add("shrnzqokjsmtkcc");
        r.add("rlyqsifroactexlyzc");
        r.add("hvagmzgwgjmztncde");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("yktkqhusnsbh");
        r.add("xzscqzxmcejqjq");
        r.add("xfsjxooclcycwcn");
        r.add("bjbedtpdcgcilwl");
        r.add("npjksoupvwuuklv");
        r.add("qmrsqbaatfzu");
        r.add("xungqrwaihorcwb");
        r.add("lywaxsogirghqgj");
        r.add("sfduuipjzhhkvtiv");
        r.add("fswnwcgwwzazfbw");
        r.add("gfzkakdfwvflslyohzi");
        r.add("outizmnucqkxdlfyxqg");
        r.add("xzscqzxmcejqjq");
        r.add("tqfqorsmvuolskkvfj");
        r.add("dvlahbxlvr");
        r.add("ghasjwxzvqjyiem");
        r.add("ltlfgqpkuaw");
        r.add("hcbgcccvxs");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("cnzvvbicdocbfzcvg");
        r.add("qfvwoqfsoidz");
        r.add("outizmnucqkxdlfyxqg");
        r.add("yktkqhusnsbh");
        r.add("gfzkakdfwvflslyohzi");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("xfsjxooclcycwcn");
        r.add("mhakcihhthaajuamlg");
        r.add("maenrdysbritmbtvyy");
        r.add("zktdtizkrcljederuxs");
        r.add("xujqjgidmzuilic");
        r.add("aizbsegmkcehkv");
        r.add("rlyqsifroactexlyzc");
        r.add("hlloonkdmanq");
        r.add("nddrscobfrojtwew");
        r.add("vvufjbgdpvfy");
        r.add("sjonqszwcwktxw");
        r.add("sgdpknswxysln");
        r.add("crexopedtp");
        r.add("wgrpqtrvgixjpajoin");
        r.add("xtujyxukoywdwu");
        r.add("dvlahbxlvr");
        r.add("bkclrgwnzmbut");
        r.add("lfdfiuwfrnevaraz");
        r.add("dgysbzweva");
        r.add("kbrkcxtvemurk");
        r.add("ejfeswctcdbrfnqy");
        r.add("iglexamfdtvt");
        r.add("vxkbsfyvywp");
        r.add("kbrkcxtvemurk");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("wrxouegcmsfbhb");
        r.add("vfvvmfxhyenhzz");
        r.add("kyqhtekrdfcigv");
        r.add("maenrdysbritmbtvyy");
        r.add("biviykdljlegtlimzil");
        r.add("rlmeprpzlifivjpdf");
        r.add("zktdtizkrcljederuxs");
        r.add("xfsjxooclcycwcn");
        r.add("wgrpqtrvgixjpajoin");
        r.add("wgrpqtrvgixjpajoin");
        r.add("dvlahbxlvr");
        r.add("elgnstionj");
        r.add("palaxwkqxstdah");
        r.add("bkclrgwnzmbut");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("fswnwcgwwzazfbw");
        r.add("eaugxiwfddefirhcf");
        r.add("pcdvbycynxymmrajlh");
        r.add("vgjxxhosif");
        r.add("uuqokimbilegfjrhzu");
        r.add("rzdgauiaqfd");
        r.add("ghasjwxzvqjyiem");
        r.add("vswlswwjpooelqttk");
        r.add("uhyatwgdcnwcxoas");
        r.add("vswlswwjpooelqttk");
        r.add("cnzvvbicdocbfzcvg");
        r.add("llpntyizbeb");
        r.add("zxyqmmiqnjnpg");
        r.add("skthxigeyrye");
        r.add("hrwroqumokjcb");
        r.add("nitcfysgzvbcz");
        r.add("dgysbzweva");
        r.add("fkgoemvsvg");
        r.add("vswlswwjpooelqttk");
        r.add("nitcfysgzvbcz");
        r.add("rzdgauiaqfd");
        r.add("bypmwgpbgmsujnlowj");
        r.add("vxkbsfyvywp");
        r.add("vvufjbgdpvfy");
        r.add("gfzkakdfwvflslyohzi");
        r.add("rsffaewcsxxocl");
        r.add("xtujyxukoywdwu");
        r.add("zrovgoudbnwrougxqz");
        r.add("pawsrhagbgzlsv");
        r.add("iglexamfdtvt");
        r.add("qacecpatcxoibelsaad");
        r.add("bjbedtpdcgcilwl");
        r.add("kyqhtekrdfcigv");
        r.add("hrwroqumokjcb");
        r.add("sfduuipjzhhkvtiv");
        r.add("iufqqsymxpsopnwuyh");
        r.add("lywaxsogirghqgj");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("vxkbsfyvywp");
        r.add("rsffaewcsxxocl");
        r.add("pcdvbycynxymmrajlh");
        r.add("lywaxsogirghqgj");
        r.add("dzstfixtnfccvwd");
        r.add("ghasjwxzvqjyiem");
        r.add("lcwvndudzxxoxzgti");
        r.add("sgdpknswxysln");
        r.add("azxxwcjitbkfkxabxv");
        r.add("tbsxdnjmagnpz");
        r.add("sjonqszwcwktxw");
        r.add("kowvhbqhmthb");
        r.add("zrovgoudbnwrougxqz");
        r.add("zktdtizkrcljederuxs");
        r.add("vpkytxfbeaqcioe");
        r.add("vfvvmfxhyenhzz");
        r.add("rzdgauiaqfd");
        r.add("zktdtizkrcljederuxs");
        r.add("wrxouegcmsfbhb");
        r.add("yjhejabudyfipd");
        r.add("qkhwynrlneksncv");
        r.add("wgrpqtrvgixjpajoin");
        r.add("vvufjbgdpvfy");
        r.add("kyqhtekrdfcigv");
        r.add("jsycwwqxrmpogurhbs");
        r.add("wgrpqtrvgixjpajoin");
        r.add("sgdpknswxysln");
        r.add("llpntyizbeb");
        r.add("biviykdljlegtlimzil");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("rbydiynhywxgdfado");
        r.add("hjnirpgylrvicvn");
        r.add("lcwvndudzxxoxzgti");
        r.add("vvufjbgdpvfy");
        r.add("eyrphlbrkw");
        r.add("uhyatwgdcnwcxoas");
        r.add("wrxouegcmsfbhb");
        r.add("hjnirpgylrvicvn");
        r.add("sgdpknswxysln");
        r.add("hvagmzgwgjmztncde");
        r.add("qacecpatcxoibelsaad");
        r.add("aizbsegmkcehkv");
        r.add("qacecpatcxoibelsaad");
        r.add("ylwwujbuoxzxr");
        r.add("hcbgcccvxs");
        r.add("fkgoemvsvg");
        r.add("xfsjxooclcycwcn");
        r.add("rlyqsifroactexlyzc");
        r.add("gfzkakdfwvflslyohzi");
        r.add("dgysbzweva");
        r.add("nddrscobfrojtwew");
        r.add("lcwvndudzxxoxzgti");
        r.add("npjksoupvwuuklv");
        r.add("sjonqszwcwktxw");
        r.add("kbrkcxtvemurk");
        r.add("qkhwynrlneksncv");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("rlyqsifroactexlyzc");
        r.add("bkclrgwnzmbut");
        r.add("qmrsqbaatfzu");
        r.add("kbrkcxtvemurk");
        r.add("dgysbzweva");
        r.add("wgrpqtrvgixjpajoin");
        r.add("vpkytxfbeaqcioe");
        r.add("zfoofhbffi");
        r.add("vvufjbgdpvfy");
        r.add("nitcfysgzvbcz");
        r.add("xzscqzxmcejqjq");
        r.add("qmrsqbaatfzu");
        r.add("kowvhbqhmthb");
        r.add("lywaxsogirghqgj");
        r.add("hlloonkdmanq");
        r.add("ltlfgqpkuaw");
        r.add("jsycwwqxrmpogurhbs");
        r.add("cmhggogvznkvwon");
        r.add("vxkbsfyvywp");
        r.add("palaxwkqxstdah");
        r.add("vvufjbgdpvfy");
        r.add("gfzkakdfwvflslyohzi");
        r.add("qacecpatcxoibelsaad");
        r.add("lfdfiuwfrnevaraz");
        r.add("gdswuqisedicz");
        r.add("eyrphlbrkw");
        r.add("zfoofhbffi");
        r.add("uhyatwgdcnwcxoas");
        r.add("rbydiynhywxgdfado");
        r.add("dgysbzweva");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("hcbgcccvxs");
        r.add("uhyatwgdcnwcxoas");
        r.add("sgdpknswxysln");
        r.add("xzscqzxmcejqjq");
        r.add("cmhggogvznkvwon");
        r.add("ghasjwxzvqjyiem");
        r.add("tqfqorsmvuolskkvfj");
        r.add("cvyebywhzrheav");
        r.add("tqfqorsmvuolskkvfj");
        r.add("xtujyxukoywdwu");
        r.add("dzstfixtnfccvwd");
        r.add("vgjxxhosif");
        r.add("biviykdljlegtlimzil");
        r.add("rlyqsifroactexlyzc");
        r.add("rlyqsifroactexlyzc");
        r.add("iysxcgoufz");
        r.add("bypmwgpbgmsujnlowj");
        r.add("biviykdljlegtlimzil");
        r.add("cgxllhichirichbzma");
        r.add("elgnstionj");
        r.add("rbydiynhywxgdfado");
        r.add("yktkqhusnsbh");
        r.add("hvagmzgwgjmztncde");
        r.add("sfduuipjzhhkvtiv");
        r.add("crexopedtp");
        r.add("eaugxiwfddefirhcf");
        r.add("hjnirpgylrvicvn");
        r.add("rzdgauiaqfd");
        r.add("mhakcihhthaajuamlg");
        r.add("zktdtizkrcljederuxs");
        r.add("vswlswwjpooelqttk");
        r.add("hqsdgjtpfxwzx");
        r.add("kyqhtekrdfcigv");
        r.add("llpntyizbeb");
        r.add("hqsdgjtpfxwzx");
        r.add("uhyatwgdcnwcxoas");
        r.add("dvlahbxlvr");
        r.add("dgysbzweva");
        r.add("maenrdysbritmbtvyy");
        r.add("crexopedtp");
        r.add("ltlfgqpkuaw");
        r.add("rlmeprpzlifivjpdf");
        r.add("zfoofhbffi");
        r.add("maenrdysbritmbtvyy");
        r.add("gfzkakdfwvflslyohzi");
        r.add("rbydiynhywxgdfado");
        r.add("jsycwwqxrmpogurhbs");
        r.add("mobwckzanokv");
        r.add("pcdvbycynxymmrajlh");
        r.add("npjksoupvwuuklv");
        r.add("zxyqmmiqnjnpg");
        r.add("dzstfixtnfccvwd");
        r.add("ejfeswctcdbrfnqy");
        r.add("rbydiynhywxgdfado");
        r.add("cvyebywhzrheav");
        r.add("vfvvmfxhyenhzz");
        r.add("kyqhtekrdfcigv");
        r.add("bypmwgpbgmsujnlowj");
        r.add("hcbgcccvxs");
        r.add("uuqokimbilegfjrhzu");
        r.add("fkgoemvsvg");
        r.add("npjksoupvwuuklv");
        r.add("eyrphlbrkw");
        r.add("sgdpknswxysln");
        r.add("mhakcihhthaajuamlg");
        r.add("vnwwgxpvmnqev");
        r.add("llpntyizbeb");
        r.add("zfoofhbffi");
        r.add("xfsjxooclcycwcn");
        r.add("kowvhbqhmthb");
        return r;
    }

    List<String> input9_2() {
        List<String> r = new ArrayList<>(1000);
        r.add("xujqjgidmzuilic");
        r.add("qacecpatcxoibelsaad");
        r.add("hvagmzgwgjmztncde");
        r.add("vswlswwjpooelqttk");
        r.add("rbydiynhywxgdfado");
        r.add("rbydiynhywxgdfado");
        r.add("yktkqhusnsbh");
        r.add("qfvwoqfsoidz");
        r.add("vgjxxhosif");
        r.add("mobwckzanokv");
        r.add("bjbedtpdcgcilwl");
        r.add("azxxwcjitbkfkxabxv");
        r.add("wgrpqtrvgixjpajoin");
        r.add("thzrjtjpousq");
        r.add("jsycwwqxrmpogurhbs");
        r.add("xtujyxukoywdwu");
        r.add("rlmeprpzlifivjpdf");
        r.add("mhakcihhthaajuamlg");
        r.add("pcdvbycynxymmrajlh");
        r.add("pawsrhagbgzlsv");
        r.add("vfvvmfxhyenhzz");
        r.add("kbrkcxtvemurk");
        r.add("qfvwoqfsoidz");
        r.add("nddrscobfrojtwew");
        r.add("bjbedtpdcgcilwl");
        r.add("tbsxdnjmagnpz");
        r.add("zktdtizkrcljederuxs");
        r.add("nitcfysgzvbcz");
        r.add("dvlahbxlvr");
        r.add("xujqjgidmzuilic");
        r.add("fkgoemvsvg");
        r.add("jsycwwqxrmpogurhbs");
        r.add("nitcfysgzvbcz");
        r.add("dzstfixtnfccvwd");
        r.add("skthxigeyrye");
        r.add("vfvvmfxhyenhzz");
        r.add("eyrphlbrkw");
        r.add("gdswuqisedicz");
        r.add("gpuvekxdscnfdferoax");
        r.add("iufqqsymxpsopnwuyh");
        r.add("biviykdljlegtlimzil");
        r.add("azxxwcjitbkfkxabxv");
        r.add("lcwvndudzxxoxzgti");
        r.add("qfvwoqfsoidz");
        r.add("maenrdysbritmbtvyy");
        r.add("hjnirpgylrvicvn");
        r.add("yktkqhusnsbh");
        r.add("hlloonkdmanq");
        r.add("outizmnucqkxdlfyxqg");
        r.add("iysxcgoufz");
        r.add("tbsxdnjmagnpz");
        r.add("biviykdljlegtlimzil");
        r.add("yjhejabudyfipd");
        r.add("lywaxsogirghqgj");
        r.add("ejfeswctcdbrfnqy");
        r.add("vvufjbgdpvfy");
        r.add("bypmwgpbgmsujnlowj");
        r.add("xfsjxooclcycwcn");
        r.add("vgjxxhosif");
        r.add("fswnwcgwwzazfbw");
        r.add("veozzplakcamuplgpx");
        r.add("cnzvvbicdocbfzcvg");
        r.add("vfvvmfxhyenhzz");
        r.add("gdswuqisedicz");
        r.add("hrwroqumokjcb");
        r.add("elgnstionj");
        r.add("qfvwoqfsoidz");
        r.add("palaxwkqxstdah");
        r.add("gpuvekxdscnfdferoax");
        r.add("rsffaewcsxxocl");
        r.add("rbydiynhywxgdfado");
        r.add("vvufjbgdpvfy");
        r.add("elgnstionj");
        r.add("tbsxdnjmagnpz");
        r.add("bkclrgwnzmbut");
        r.add("nddrscobfrojtwew");
        r.add("gikbbcuucfceho");
        r.add("pcdvbycynxymmrajlh");
        r.add("bkclrgwnzmbut");
        r.add("xujqjgidmzuilic");
        r.add("hrwroqumokjcb");
        r.add("nitcfysgzvbcz");
        r.add("lcwvndudzxxoxzgti");
        r.add("rlyqsifroactexlyzc");
        r.add("iglexamfdtvt");
        r.add("qmrsqbaatfzu");
        r.add("hqsdgjtpfxwzx");
        r.add("bkclrgwnzmbut");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("iglexamfdtvt");
        r.add("rsffaewcsxxocl");
        r.add("sjonqszwcwktxw");
        r.add("maenrdysbritmbtvyy");
        r.add("kyqhtekrdfcigv");
        r.add("hrwroqumokjcb");
        r.add("vswlswwjpooelqttk");
        r.add("fswnwcgwwzazfbw");
        r.add("hvagmzgwgjmztncde");
        r.add("iufqqsymxpsopnwuyh");
        r.add("xzscqzxmcejqjq");
        r.add("vpkytxfbeaqcioe");
        r.add("qacecpatcxoibelsaad");
        r.add("llpntyizbeb");
        r.add("rsffaewcsxxocl");
        r.add("xtujyxukoywdwu");
        r.add("zfoofhbffi");
        r.add("skthxigeyrye");
        r.add("uuqokimbilegfjrhzu");
        r.add("xfsjxooclcycwcn");
        r.add("xzscqzxmcejqjq");
        r.add("outizmnucqkxdlfyxqg");
        r.add("qmrsqbaatfzu");
        r.add("zktdtizkrcljederuxs");
        r.add("bkclrgwnzmbut");
        r.add("pinxwmmeifueviczi");
        r.add("vfvvmfxhyenhzz");
        r.add("zxyqmmiqnjnpg");
        r.add("ghasjwxzvqjyiem");
        r.add("sjonqszwcwktxw");
        r.add("yjhejabudyfipd");
        r.add("rlyqsifroactexlyzc");
        r.add("wgrpqtrvgixjpajoin");
        r.add("zktdtizkrcljederuxs");
        r.add("cmhggogvznkvwon");
        r.add("cmhggogvznkvwon");
        r.add("pcdvbycynxymmrajlh");
        r.add("qacecpatcxoibelsaad");
        r.add("zxyqmmiqnjnpg");
        r.add("ylwwujbuoxzxr");
        r.add("cvyebywhzrheav");
        r.add("vswlswwjpooelqttk");
        r.add("rbydiynhywxgdfado");
        r.add("zfoofhbffi");
        r.add("cvyebywhzrheav");
        r.add("kowvhbqhmthb");
        r.add("mhakcihhthaajuamlg");
        r.add("vnwwgxpvmnqev");
        r.add("qmrsqbaatfzu");
        r.add("gpuvekxdscnfdferoax");
        r.add("vswlswwjpooelqttk");
        r.add("pinxwmmeifueviczi");
        r.add("rbydiynhywxgdfado");
        r.add("ylwwujbuoxzxr");
        r.add("uuqokimbilegfjrhzu");
        r.add("pinxwmmeifueviczi");
        r.add("xfsjxooclcycwcn");
        r.add("pcdvbycynxymmrajlh");
        r.add("fkgoemvsvg");
        r.add("vnwwgxpvmnqev");
        r.add("zktdtizkrcljederuxs");
        r.add("bkclrgwnzmbut");
        r.add("rsffaewcsxxocl");
        r.add("bjbedtpdcgcilwl");
        r.add("nitcfysgzvbcz");
        r.add("vxkbsfyvywp");
        r.add("rbydiynhywxgdfado");
        r.add("thzrjtjpousq");
        r.add("yktkqhusnsbh");
        r.add("elgnstionj");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("npjksoupvwuuklv");
        r.add("dvlahbxlvr");
        r.add("bjbedtpdcgcilwl");
        r.add("gdswuqisedicz");
        r.add("gikbbcuucfceho");
        r.add("qfvwoqfsoidz");
        r.add("gikbbcuucfceho");
        r.add("rlmeprpzlifivjpdf");
        r.add("skthxigeyrye");
        r.add("shrnzqokjsmtkcc");
        r.add("veozzplakcamuplgpx");
        r.add("bkclrgwnzmbut");
        r.add("shrnzqokjsmtkcc");
        r.add("jsycwwqxrmpogurhbs");
        r.add("vnwwgxpvmnqev");
        r.add("kowvhbqhmthb");
        r.add("rsffaewcsxxocl");
        r.add("lfdfiuwfrnevaraz");
        r.add("yjhejabudyfipd");
        r.add("yjhejabudyfipd");
        r.add("rlyqsifroactexlyzc");
        r.add("veozzplakcamuplgpx");
        r.add("cnzvvbicdocbfzcvg");
        r.add("zxyqmmiqnjnpg");
        r.add("yjhejabudyfipd");
        r.add("yjhejabudyfipd");
        r.add("hqsdgjtpfxwzx");
        r.add("aizbsegmkcehkv");
        r.add("iysxcgoufz");
        r.add("hvagmzgwgjmztncde");
        r.add("iysxcgoufz");
        r.add("vvufjbgdpvfy");
        r.add("uuqokimbilegfjrhzu");
        r.add("veozzplakcamuplgpx");
        r.add("rsffaewcsxxocl");
        r.add("vnwwgxpvmnqev");
        r.add("kowvhbqhmthb");
        r.add("qmrsqbaatfzu");
        r.add("outizmnucqkxdlfyxqg");
        r.add("vswlswwjpooelqttk");
        r.add("rlyqsifroactexlyzc");
        r.add("veozzplakcamuplgpx");
        r.add("yktkqhusnsbh");
        r.add("mhakcihhthaajuamlg");
        r.add("wgrpqtrvgixjpajoin");
        r.add("fswnwcgwwzazfbw");
        r.add("qmrsqbaatfzu");
        r.add("zrovgoudbnwrougxqz");
        r.add("eyrphlbrkw");
        r.add("kowvhbqhmthb");
        r.add("rsffaewcsxxocl");
        r.add("zxyqmmiqnjnpg");
        r.add("bjbedtpdcgcilwl");
        r.add("uhyatwgdcnwcxoas");
        r.add("xtujyxukoywdwu");
        r.add("gdswuqisedicz");
        r.add("xfsjxooclcycwcn");
        r.add("sjonqszwcwktxw");
        r.add("aizbsegmkcehkv");
        r.add("crexopedtp");
        r.add("zrovgoudbnwrougxqz");
        r.add("rbydiynhywxgdfado");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("hcbgcccvxs");
        r.add("npjksoupvwuuklv");
        r.add("gdswuqisedicz");
        r.add("xungqrwaihorcwb");
        r.add("sfduuipjzhhkvtiv");
        r.add("vpkytxfbeaqcioe");
        r.add("uuqokimbilegfjrhzu");
        r.add("hjnirpgylrvicvn");
        r.add("maenrdysbritmbtvyy");
        r.add("qmrsqbaatfzu");
        r.add("kowvhbqhmthb");
        r.add("nddrscobfrojtwew");
        r.add("tqfqorsmvuolskkvfj");
        r.add("ylwwujbuoxzxr");
        r.add("iysxcgoufz");
        r.add("jsycwwqxrmpogurhbs");
        r.add("sjonqszwcwktxw");
        r.add("vfvvmfxhyenhzz");
        r.add("mobwckzanokv");
        r.add("rlyqsifroactexlyzc");
        r.add("iglexamfdtvt");
        r.add("maenrdysbritmbtvyy");
        r.add("wrxouegcmsfbhb");
        r.add("pinxwmmeifueviczi");
        r.add("npjksoupvwuuklv");
        r.add("rzdgauiaqfd");
        r.add("zxyqmmiqnjnpg");
        r.add("qkhwynrlneksncv");
        r.add("veozzplakcamuplgpx");
        r.add("xungqrwaihorcwb");
        r.add("lywaxsogirghqgj");
        r.add("kowvhbqhmthb");
        r.add("llpntyizbeb");
        r.add("xtujyxukoywdwu");
        r.add("ejfeswctcdbrfnqy");
        r.add("hjnirpgylrvicvn");
        r.add("npjksoupvwuuklv");
        r.add("vnwwgxpvmnqev");
        r.add("dzstfixtnfccvwd");
        r.add("azxxwcjitbkfkxabxv");
        r.add("jsycwwqxrmpogurhbs");
        r.add("xujqjgidmzuilic");
        r.add("vgjxxhosif");
        r.add("rzdgauiaqfd");
        r.add("hlloonkdmanq");
        r.add("kbrkcxtvemurk");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("aizbsegmkcehkv");
        r.add("gfzkakdfwvflslyohzi");
        r.add("hqsdgjtpfxwzx");
        r.add("mobwckzanokv");
        r.add("qmrsqbaatfzu");
        r.add("hjnirpgylrvicvn");
        r.add("zxyqmmiqnjnpg");
        r.add("pawsrhagbgzlsv");
        r.add("kowvhbqhmthb");
        r.add("zxyqmmiqnjnpg");
        r.add("dvlahbxlvr");
        r.add("dgysbzweva");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("crexopedtp");
        r.add("vgjxxhosif");
        r.add("kyqhtekrdfcigv");
        r.add("vxkbsfyvywp");
        r.add("gfzkakdfwvflslyohzi");
        r.add("kbrkcxtvemurk");
        r.add("biviykdljlegtlimzil");
        r.add("fkgoemvsvg");
        r.add("outizmnucqkxdlfyxqg");
        r.add("ltlfgqpkuaw");
        r.add("hcbgcccvxs");
        r.add("xzscqzxmcejqjq");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("zrovgoudbnwrougxqz");
        r.add("sfduuipjzhhkvtiv");
        r.add("qmrsqbaatfzu");
        r.add("lcwvndudzxxoxzgti");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("vxkbsfyvywp");
        r.add("uhyatwgdcnwcxoas");
        r.add("eyrphlbrkw");
        r.add("gpuvekxdscnfdferoax");
        r.add("rzdgauiaqfd");
        r.add("cgxllhichirichbzma");
        r.add("bypmwgpbgmsujnlowj");
        r.add("hjnirpgylrvicvn");
        r.add("hvagmzgwgjmztncde");
        r.add("qmrsqbaatfzu");
        r.add("pcdvbycynxymmrajlh");
        r.add("rzdgauiaqfd");
        r.add("vvufjbgdpvfy");
        r.add("fkgoemvsvg");
        r.add("vxkbsfyvywp");
        r.add("maenrdysbritmbtvyy");
        r.add("rsffaewcsxxocl");
        r.add("hlloonkdmanq");
        r.add("tqfqorsmvuolskkvfj");
        r.add("kowvhbqhmthb");
        r.add("hlloonkdmanq");
        r.add("gdswuqisedicz");
        r.add("npjksoupvwuuklv");
        r.add("pcdvbycynxymmrajlh");
        r.add("vxkbsfyvywp");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("rlmeprpzlifivjpdf");
        r.add("azxxwcjitbkfkxabxv");
        r.add("rsffaewcsxxocl");
        r.add("ejfeswctcdbrfnqy");
        r.add("xzscqzxmcejqjq");
        r.add("thzrjtjpousq");
        r.add("crexopedtp");
        r.add("gfzkakdfwvflslyohzi");
        r.add("lfdfiuwfrnevaraz");
        r.add("hrwroqumokjcb");
        r.add("rlyqsifroactexlyzc");
        r.add("lfdfiuwfrnevaraz");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("ghasjwxzvqjyiem");
        r.add("pinxwmmeifueviczi");
        r.add("skthxigeyrye");
        r.add("fswnwcgwwzazfbw");
        r.add("bjbedtpdcgcilwl");
        r.add("npjksoupvwuuklv");
        r.add("qacecpatcxoibelsaad");
        r.add("pinxwmmeifueviczi");
        r.add("vfvvmfxhyenhzz");
        r.add("qfvwoqfsoidz");
        r.add("iglexamfdtvt");
        r.add("fswnwcgwwzazfbw");
        r.add("eaugxiwfddefirhcf");
        r.add("veozzplakcamuplgpx");
        r.add("cgxllhichirichbzma");
        r.add("pinxwmmeifueviczi");
        r.add("uhyatwgdcnwcxoas");
        r.add("bypmwgpbgmsujnlowj");
        r.add("vswlswwjpooelqttk");
        r.add("biviykdljlegtlimzil");
        r.add("rzdgauiaqfd");
        r.add("xungqrwaihorcwb");
        r.add("cvyebywhzrheav");
        r.add("qkhwynrlneksncv");
        r.add("cmhggogvznkvwon");
        r.add("llpntyizbeb");
        r.add("ghasjwxzvqjyiem");
        r.add("wgrpqtrvgixjpajoin");
        r.add("vgjxxhosif");
        r.add("zrovgoudbnwrougxqz");
        r.add("vnwwgxpvmnqev");
        r.add("cnzvvbicdocbfzcvg");
        r.add("vpkytxfbeaqcioe");
        r.add("gdswuqisedicz");
        r.add("llpntyizbeb");
        r.add("rbydiynhywxgdfado");
        r.add("rbydiynhywxgdfado");
        r.add("sfduuipjzhhkvtiv");
        r.add("mhakcihhthaajuamlg");
        r.add("zfoofhbffi");
        r.add("dvlahbxlvr");
        r.add("kbrkcxtvemurk");
        r.add("hcbgcccvxs");
        r.add("eyrphlbrkw");
        r.add("hvagmzgwgjmztncde");
        r.add("rbydiynhywxgdfado");
        r.add("hvagmzgwgjmztncde");
        r.add("ltlfgqpkuaw");
        r.add("fswnwcgwwzazfbw");
        r.add("ghasjwxzvqjyiem");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("lfdfiuwfrnevaraz");
        r.add("ylwwujbuoxzxr");
        r.add("crexopedtp");
        r.add("palaxwkqxstdah");
        r.add("hjnirpgylrvicvn");
        r.add("hcbgcccvxs");
        r.add("bkclrgwnzmbut");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("crexopedtp");
        r.add("mobwckzanokv");
        r.add("iufqqsymxpsopnwuyh");
        r.add("hlloonkdmanq");
        r.add("lcwvndudzxxoxzgti");
        r.add("yjhejabudyfipd");
        r.add("npjksoupvwuuklv");
        r.add("biviykdljlegtlimzil");
        r.add("vpkytxfbeaqcioe");
        r.add("npjksoupvwuuklv");
        r.add("tbsxdnjmagnpz");
        r.add("tqfqorsmvuolskkvfj");
        r.add("dgysbzweva");
        r.add("azxxwcjitbkfkxabxv");
        r.add("yktkqhusnsbh");
        r.add("wrxouegcmsfbhb");
        r.add("fkgoemvsvg");
        r.add("yjhejabudyfipd");
        r.add("azxxwcjitbkfkxabxv");
        r.add("hvagmzgwgjmztncde");
        r.add("vswlswwjpooelqttk");
        r.add("yjhejabudyfipd");
        r.add("uhyatwgdcnwcxoas");
        r.add("vnwwgxpvmnqev");
        r.add("npjksoupvwuuklv");
        r.add("eyrphlbrkw");
        r.add("ghasjwxzvqjyiem");
        r.add("kbrkcxtvemurk");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("hvagmzgwgjmztncde");
        r.add("qfvwoqfsoidz");
        r.add("lfdfiuwfrnevaraz");
        r.add("skthxigeyrye");
        r.add("hjnirpgylrvicvn");
        r.add("gdswuqisedicz");
        r.add("vgjxxhosif");
        r.add("tbsxdnjmagnpz");
        r.add("lfdfiuwfrnevaraz");
        r.add("jsycwwqxrmpogurhbs");
        r.add("hvagmzgwgjmztncde");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("sgdpknswxysln");
        r.add("cgxllhichirichbzma");
        r.add("kbrkcxtvemurk");
        r.add("hrwroqumokjcb");
        r.add("gikbbcuucfceho");
        r.add("zxyqmmiqnjnpg");
        r.add("xfsjxooclcycwcn");
        r.add("hqsdgjtpfxwzx");
        r.add("eaugxiwfddefirhcf");
        r.add("tqfqorsmvuolskkvfj");
        r.add("dzstfixtnfccvwd");
        r.add("vswlswwjpooelqttk");
        r.add("bypmwgpbgmsujnlowj");
        r.add("cvyebywhzrheav");
        r.add("qkhwynrlneksncv");
        r.add("gpuvekxdscnfdferoax");
        r.add("ylwwujbuoxzxr");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("pcdvbycynxymmrajlh");
        r.add("qfvwoqfsoidz");
        r.add("yktkqhusnsbh");
        r.add("hvagmzgwgjmztncde");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("kbrkcxtvemurk");
        r.add("bjbedtpdcgcilwl");
        r.add("pinxwmmeifueviczi");
        r.add("vvufjbgdpvfy");
        r.add("zfoofhbffi");
        r.add("zxyqmmiqnjnpg");
        r.add("vswlswwjpooelqttk");
        r.add("rzdgauiaqfd");
        r.add("xfsjxooclcycwcn");
        r.add("skthxigeyrye");
        r.add("rzdgauiaqfd");
        r.add("qmrsqbaatfzu");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("hqsdgjtpfxwzx");
        r.add("gikbbcuucfceho");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("kyqhtekrdfcigv");
        r.add("qfvwoqfsoidz");
        r.add("hvagmzgwgjmztncde");
        r.add("hjnirpgylrvicvn");
        r.add("outizmnucqkxdlfyxqg");
        r.add("qmrsqbaatfzu");
        r.add("pcdvbycynxymmrajlh");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("jsycwwqxrmpogurhbs");
        r.add("hcbgcccvxs");
        r.add("azxxwcjitbkfkxabxv");
        r.add("biviykdljlegtlimzil");
        r.add("gfzkakdfwvflslyohzi");
        r.add("tqfqorsmvuolskkvfj");
        r.add("sgdpknswxysln");
        r.add("veozzplakcamuplgpx");
        r.add("rzdgauiaqfd");
        r.add("hlloonkdmanq");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("hjnirpgylrvicvn");
        r.add("zrovgoudbnwrougxqz");
        r.add("yjhejabudyfipd");
        r.add("veozzplakcamuplgpx");
        r.add("lcwvndudzxxoxzgti");
        r.add("shrnzqokjsmtkcc");
        r.add("xujqjgidmzuilic");
        r.add("gikbbcuucfceho");
        r.add("kbrkcxtvemurk");
        r.add("zktdtizkrcljederuxs");
        r.add("uhyatwgdcnwcxoas");
        r.add("vnwwgxpvmnqev");
        r.add("cmhggogvznkvwon");
        r.add("cnzvvbicdocbfzcvg");
        r.add("vswlswwjpooelqttk");
        r.add("skthxigeyrye");
        r.add("xtujyxukoywdwu");
        r.add("rlyqsifroactexlyzc");
        r.add("hqsdgjtpfxwzx");
        r.add("ltlfgqpkuaw");
        r.add("xujqjgidmzuilic");
        r.add("nitcfysgzvbcz");
        r.add("palaxwkqxstdah");
        r.add("cvyebywhzrheav");
        r.add("jsycwwqxrmpogurhbs");
        r.add("aizbsegmkcehkv");
        r.add("dvlahbxlvr");
        r.add("mhakcihhthaajuamlg");
        r.add("hcbgcccvxs");
        r.add("shrnzqokjsmtkcc");
        r.add("yjhejabudyfipd");
        r.add("pawsrhagbgzlsv");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("llpntyizbeb");
        r.add("bypmwgpbgmsujnlowj");
        r.add("uuqokimbilegfjrhzu");
        r.add("ylwwujbuoxzxr");
        r.add("gdswuqisedicz");
        r.add("hcbgcccvxs");
        r.add("qmrsqbaatfzu");
        r.add("veozzplakcamuplgpx");
        r.add("vxkbsfyvywp");
        r.add("tbsxdnjmagnpz");
        r.add("mobwckzanokv");
        r.add("rlyqsifroactexlyzc");
        r.add("zxyqmmiqnjnpg");
        r.add("pawsrhagbgzlsv");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("wgrpqtrvgixjpajoin");
        r.add("gpuvekxdscnfdferoax");
        r.add("qmrsqbaatfzu");
        r.add("skthxigeyrye");
        r.add("lywaxsogirghqgj");
        r.add("mhakcihhthaajuamlg");
        r.add("outizmnucqkxdlfyxqg");
        r.add("bjbedtpdcgcilwl");
        r.add("vnwwgxpvmnqev");
        r.add("hqsdgjtpfxwzx");
        r.add("gfzkakdfwvflslyohzi");
        r.add("kyqhtekrdfcigv");
        r.add("eyrphlbrkw");
        r.add("rlmeprpzlifivjpdf");
        r.add("mobwckzanokv");
        r.add("hvagmzgwgjmztncde");
        r.add("bjbedtpdcgcilwl");
        r.add("hcbgcccvxs");
        r.add("bypmwgpbgmsujnlowj");
        r.add("lcwvndudzxxoxzgti");
        r.add("sfduuipjzhhkvtiv");
        r.add("cmhggogvznkvwon");
        r.add("qacecpatcxoibelsaad");
        r.add("tqfqorsmvuolskkvfj");
        r.add("bjbedtpdcgcilwl");
        r.add("lywaxsogirghqgj");
        r.add("kowvhbqhmthb");
        r.add("ylwwujbuoxzxr");
        r.add("cgxllhichirichbzma");
        r.add("maenrdysbritmbtvyy");
        r.add("outizmnucqkxdlfyxqg");
        r.add("nitcfysgzvbcz");
        r.add("hvagmzgwgjmztncde");
        r.add("sgdpknswxysln");
        r.add("wgrpqtrvgixjpajoin");
        r.add("lywaxsogirghqgj");
        r.add("dgysbzweva");
        r.add("hcbgcccvxs");
        r.add("cmhggogvznkvwon");
        r.add("gdswuqisedicz");
        r.add("zrovgoudbnwrougxqz");
        r.add("vpkytxfbeaqcioe");
        r.add("gdswuqisedicz");
        r.add("zrovgoudbnwrougxqz");
        r.add("crexopedtp");
        r.add("mobwckzanokv");
        r.add("zfoofhbffi");
        r.add("hcbgcccvxs");
        r.add("rlyqsifroactexlyzc");
        r.add("ltlfgqpkuaw");
        r.add("ylwwujbuoxzxr");
        r.add("gikbbcuucfceho");
        r.add("cgxllhichirichbzma");
        r.add("gdswuqisedicz");
        r.add("vswlswwjpooelqttk");
        r.add("lfdfiuwfrnevaraz");
        r.add("sjonqszwcwktxw");
        r.add("yjhejabudyfipd");
        r.add("vswlswwjpooelqttk");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("cmhggogvznkvwon");
        r.add("fkgoemvsvg");
        r.add("hvagmzgwgjmztncde");
        r.add("cgxllhichirichbzma");
        r.add("iufqqsymxpsopnwuyh");
        r.add("iysxcgoufz");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("wgrpqtrvgixjpajoin");
        r.add("ltlfgqpkuaw");
        r.add("palaxwkqxstdah");
        r.add("vxkbsfyvywp");
        r.add("iufqqsymxpsopnwuyh");
        r.add("vswlswwjpooelqttk");
        r.add("npjksoupvwuuklv");
        r.add("skthxigeyrye");
        r.add("ltlfgqpkuaw");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("dgysbzweva");
        r.add("nitcfysgzvbcz");
        r.add("vswlswwjpooelqttk");
        r.add("hvagmzgwgjmztncde");
        r.add("wgrpqtrvgixjpajoin");
        r.add("gdswuqisedicz");
        r.add("iysxcgoufz");
        r.add("llpntyizbeb");
        r.add("gikbbcuucfceho");
        r.add("npjksoupvwuuklv");
        r.add("kbrkcxtvemurk");
        r.add("tqfqorsmvuolskkvfj");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("yjhejabudyfipd");
        r.add("kowvhbqhmthb");
        r.add("xtujyxukoywdwu");
        r.add("qfvwoqfsoidz");
        r.add("qfvwoqfsoidz");
        r.add("vswlswwjpooelqttk");
        r.add("hvagmzgwgjmztncde");
        r.add("nitcfysgzvbcz");
        r.add("yjhejabudyfipd");
        r.add("vnwwgxpvmnqev");
        r.add("ylwwujbuoxzxr");
        r.add("veozzplakcamuplgpx");
        r.add("qfvwoqfsoidz");
        r.add("lfdfiuwfrnevaraz");
        r.add("mobwckzanokv");
        r.add("rbydiynhywxgdfado");
        r.add("iglexamfdtvt");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("zfoofhbffi");
        r.add("cvyebywhzrheav");
        r.add("eyrphlbrkw");
        r.add("elgnstionj");
        r.add("npjksoupvwuuklv");
        r.add("iysxcgoufz");
        r.add("eaugxiwfddefirhcf");
        r.add("palaxwkqxstdah");
        r.add("zktdtizkrcljederuxs");
        r.add("palaxwkqxstdah");
        r.add("dgysbzweva");
        r.add("hlloonkdmanq");
        r.add("gdswuqisedicz");
        r.add("outizmnucqkxdlfyxqg");
        r.add("llpntyizbeb");
        r.add("vgjxxhosif");
        r.add("skthxigeyrye");
        r.add("lfdfiuwfrnevaraz");
        r.add("dgysbzweva");
        r.add("vnwwgxpvmnqev");
        r.add("nddrscobfrojtwew");
        r.add("zxyqmmiqnjnpg");
        r.add("ltlfgqpkuaw");
        r.add("lywaxsogirghqgj");
        r.add("llpntyizbeb");
        r.add("wgrpqtrvgixjpajoin");
        r.add("azxxwcjitbkfkxabxv");
        r.add("ltlfgqpkuaw");
        r.add("maenrdysbritmbtvyy");
        r.add("llpntyizbeb");
        r.add("mhakcihhthaajuamlg");
        r.add("thzrjtjpousq");
        r.add("znwxmwuzbzhgqoikovz");
        r.add("bypmwgpbgmsujnlowj");
        r.add("rlmeprpzlifivjpdf");
        r.add("hlloonkdmanq");
        r.add("xujqjgidmzuilic");
        r.add("vgjxxhosif");
        r.add("vfvvmfxhyenhzz");
        r.add("eaugxiwfddefirhcf");
        r.add("ejfeswctcdbrfnqy");
        r.add("thzrjtjpousq");
        r.add("dzstfixtnfccvwd");
        r.add("vswlswwjpooelqttk");
        r.add("fswnwcgwwzazfbw");
        r.add("gfzkakdfwvflslyohzi");
        r.add("xungqrwaihorcwb");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("bjbedtpdcgcilwl");
        r.add("hjnirpgylrvicvn");
        r.add("kyqhtekrdfcigv");
        r.add("pawsrhagbgzlsv");
        r.add("xujqjgidmzuilic");
        r.add("kowvhbqhmthb");
        r.add("ltlfgqpkuaw");
        r.add("fswnwcgwwzazfbw");
        r.add("lcwvndudzxxoxzgti");
        r.add("vxkbsfyvywp");
        r.add("nitcfysgzvbcz");
        r.add("fkgoemvsvg");
        r.add("wgrpqtrvgixjpajoin");
        r.add("cvyebywhzrheav");
        r.add("eaugxiwfddefirhcf");
        r.add("shrnzqokjsmtkcc");
        r.add("sgdpknswxysln");
        r.add("cnzvvbicdocbfzcvg");
        r.add("shrnzqokjsmtkcc");
        r.add("xtujyxukoywdwu");
        r.add("rlyqsifroactexlyzc");
        r.add("hlloonkdmanq");
        r.add("bkclrgwnzmbut");
        r.add("zxyqmmiqnjnpg");
        r.add("skthxigeyrye");
        r.add("ltlfgqpkuaw");
        r.add("hjnirpgylrvicvn");
        r.add("wrxouegcmsfbhb");
        r.add("maenrdysbritmbtvyy");
        r.add("ejfeswctcdbrfnqy");
        r.add("kbrkcxtvemurk");
        r.add("rlmeprpzlifivjpdf");
        r.add("pawsrhagbgzlsv");
        r.add("rlyqsifroactexlyzc");
        r.add("biviykdljlegtlimzil");
        r.add("ghasjwxzvqjyiem");
        r.add("xzscqzxmcejqjq");
        r.add("pcdvbycynxymmrajlh");
        r.add("rsffaewcsxxocl");
        r.add("rsffaewcsxxocl");
        r.add("sfduuipjzhhkvtiv");
        r.add("xfsjxooclcycwcn");
        r.add("qmrsqbaatfzu");
        r.add("sjonqszwcwktxw");
        r.add("iglexamfdtvt");
        r.add("vnwwgxpvmnqev");
        r.add("mobwckzanokv");
        r.add("skthxigeyrye");
        r.add("vfvvmfxhyenhzz");
        r.add("yjhejabudyfipd");
        r.add("jsycwwqxrmpogurhbs");
        r.add("hjnirpgylrvicvn");
        r.add("kowvhbqhmthb");
        r.add("outizmnucqkxdlfyxqg");
        r.add("gdswuqisedicz");
        r.add("vgjxxhosif");
        r.add("rlmeprpzlifivjpdf");
        r.add("nddrscobfrojtwew");
        r.add("ltlfgqpkuaw");
        r.add("palaxwkqxstdah");
        r.add("hcbgcccvxs");
        r.add("gfzkakdfwvflslyohzi");
        r.add("biviykdljlegtlimzil");
        r.add("gpuvekxdscnfdferoax");
        r.add("palaxwkqxstdah");
        r.add("xzscqzxmcejqjq");
        r.add("gdswuqisedicz");
        r.add("zfoofhbffi");
        r.add("lywaxsogirghqgj");
        r.add("iglexamfdtvt");
        r.add("mhakcihhthaajuamlg");
        r.add("dvlahbxlvr");
        r.add("npjksoupvwuuklv");
        r.add("sgdpknswxysln");
        r.add("qfvwoqfsoidz");
        r.add("xfsjxooclcycwcn");
        r.add("yjhejabudyfipd");
        r.add("hqsdgjtpfxwzx");
        r.add("azxxwcjitbkfkxabxv");
        r.add("hlloonkdmanq");
        r.add("fkgoemvsvg");
        r.add("kbrkcxtvemurk");
        r.add("hqsdgjtpfxwzx");
        r.add("fswnwcgwwzazfbw");
        r.add("kbrkcxtvemurk");
        r.add("elgnstionj");
        r.add("nddrscobfrojtwew");
        r.add("biviykdljlegtlimzil");
        r.add("palaxwkqxstdah");
        r.add("xfsjxooclcycwcn");
        r.add("pawsrhagbgzlsv");
        r.add("vfvvmfxhyenhzz");
        r.add("vpkytxfbeaqcioe");
        r.add("aizbsegmkcehkv");
        r.add("sjonqszwcwktxw");
        r.add("gikbbcuucfceho");
        r.add("ghasjwxzvqjyiem");
        r.add("lywaxsogirghqgj");
        r.add("hlloonkdmanq");
        r.add("hlloonkdmanq");
        r.add("vgjxxhosif");
        r.add("xzscqzxmcejqjq");
        r.add("qfvwoqfsoidz");
        r.add("iysxcgoufz");
        r.add("vpkytxfbeaqcioe");
        r.add("rlmeprpzlifivjpdf");
        r.add("gikbbcuucfceho");
        r.add("elgnstionj");
        r.add("rbydiynhywxgdfado");
        r.add("hjnirpgylrvicvn");
        r.add("wrxouegcmsfbhb");
        r.add("iufqqsymxpsopnwuyh");
        r.add("dvlahbxlvr");
        r.add("gfzkakdfwvflslyohzi");
        r.add("gfzkakdfwvflslyohzi");
        r.add("sjonqszwcwktxw");
        r.add("gfzkakdfwvflslyohzi");
        r.add("lywaxsogirghqgj");
        r.add("xujqjgidmzuilic");
        r.add("rsffaewcsxxocl");
        r.add("wgrpqtrvgixjpajoin");
        r.add("maenrdysbritmbtvyy");
        r.add("lcwvndudzxxoxzgti");
        r.add("hcbgcccvxs");
        r.add("iysxcgoufz");
        r.add("vgjxxhosif");
        r.add("maenrdysbritmbtvyy");
        r.add("eaugxiwfddefirhcf");
        r.add("zxyqmmiqnjnpg");
        r.add("sfduuipjzhhkvtiv");
        r.add("yjhejabudyfipd");
        r.add("ghasjwxzvqjyiem");
        r.add("kyqhtekrdfcigv");
        r.add("cvyebywhzrheav");
        r.add("crexopedtp");
        r.add("zktdtizkrcljederuxs");
        r.add("gfzkakdfwvflslyohzi");
        r.add("ejfeswctcdbrfnqy");
        r.add("kyqhtekrdfcigv");
        r.add("hcbgcccvxs");
        r.add("hrwroqumokjcb");
        r.add("zxyqmmiqnjnpg");
        r.add("vswlswwjpooelqttk");
        r.add("cvyebywhzrheav");
        r.add("shrnzqokjsmtkcc");
        r.add("yktkqhusnsbh");
        r.add("eaugxiwfddefirhcf");
        r.add("rlmeprpzlifivjpdf");
        r.add("dvlahbxlvr");
        r.add("ghasjwxzvqjyiem");
        r.add("zxyqmmiqnjnpg");
        r.add("azxxwcjitbkfkxabxv");
        r.add("gpuvekxdscnfdferoax");
        r.add("cmhggogvznkvwon");
        r.add("sjonqszwcwktxw");
        r.add("thzrjtjpousq");
        r.add("pawsrhagbgzlsv");
        r.add("hvagmzgwgjmztncde");
        r.add("uhyatwgdcnwcxoas");
        r.add("fkgoemvsvg");
        r.add("xfsjxooclcycwcn");
        r.add("vfvvmfxhyenhzz");
        r.add("hjnirpgylrvicvn");
        r.add("vfvvmfxhyenhzz");
        r.add("sjonqszwcwktxw");
        r.add("iysxcgoufz");
        r.add("palaxwkqxstdah");
        r.add("palaxwkqxstdah");
        r.add("iufqqsymxpsopnwuyh");
        r.add("llpntyizbeb");
        r.add("qacecpatcxoibelsaad");
        r.add("bypmwgpbgmsujnlowj");
        r.add("dvlahbxlvr");
        r.add("xzscqzxmcejqjq");
        r.add("sjonqszwcwktxw");
        r.add("aizbsegmkcehkv");
        r.add("vswlswwjpooelqttk");
        r.add("hqsdgjtpfxwzx");
        r.add("ejfeswctcdbrfnqy");
        r.add("xungqrwaihorcwb");
        r.add("qkhwynrlneksncv");
        r.add("xfsjxooclcycwcn");
        r.add("rsffaewcsxxocl");
        r.add("nitcfysgzvbcz");
        r.add("vgjxxhosif");
        r.add("xungqrwaihorcwb");
        r.add("eaugxiwfddefirhcf");
        r.add("outizmnucqkxdlfyxqg");
        r.add("uhyatwgdcnwcxoas");
        r.add("pinxwmmeifueviczi");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("rbydiynhywxgdfado");
        r.add("gfzkakdfwvflslyohzi");
        r.add("wrxouegcmsfbhb");
        r.add("rsffaewcsxxocl");
        r.add("vgjxxhosif");
        r.add("llpntyizbeb");
        r.add("bkclrgwnzmbut");
        r.add("mhakcihhthaajuamlg");
        r.add("zfoofhbffi");
        r.add("aizbsegmkcehkv");
        r.add("xfsjxooclcycwcn");
        r.add("ltlfgqpkuaw");
        r.add("zrovgoudbnwrougxqz");
        r.add("pawsrhagbgzlsv");
        r.add("rbydiynhywxgdfado");
        r.add("zktdtizkrcljederuxs");
        r.add("nitcfysgzvbcz");
        r.add("vvufjbgdpvfy");
        r.add("uhyatwgdcnwcxoas");
        r.add("shrnzqokjsmtkcc");
        r.add("mhakcihhthaajuamlg");
        r.add("mhakcihhthaajuamlg");
        r.add("uhyatwgdcnwcxoas");
        r.add("vxkbsfyvywp");
        r.add("gdswuqisedicz");
        r.add("eyrphlbrkw");
        r.add("dgysbzweva");
        r.add("tqfqorsmvuolskkvfj");
        r.add("vgjxxhosif");
        r.add("xungqrwaihorcwb");
        r.add("mhakcihhthaajuamlg");
        r.add("zrovgoudbnwrougxqz");
        r.add("bypmwgpbgmsujnlowj");
        r.add("vgjxxhosif");
        r.add("auvffqnubmjhjsqqnwd");
        r.add("iglexamfdtvt");
        r.add("kyqhtekrdfcigv");
        r.add("elgnstionj");
        r.add("rnjifiaoeaweiqoxmsx");
        r.add("veozzplakcamuplgpx");
        r.add("vnwwgxpvmnqev");
        r.add("bkclrgwnzmbut");
        r.add("lfdfiuwfrnevaraz");
        r.add("bypmwgpbgmsujnlowj");
        r.add("qmrsqbaatfzu");
        r.add("eaugxiwfddefirhcf");
        r.add("lywaxsogirghqgj");
        r.add("sgdpknswxysln");
        r.add("hjnirpgylrvicvn");
        r.add("rzdgauiaqfd");
        r.add("cmhggogvznkvwon");
        r.add("gikbbcuucfceho");
        r.add("hrwroqumokjcb");
        r.add("hqsdgjtpfxwzx");
        r.add("qmrsqbaatfzu");
        r.add("palaxwkqxstdah");
        r.add("dzstfixtnfccvwd");
        r.add("rsffaewcsxxocl");
        r.add("bkclrgwnzmbut");
        r.add("vswlswwjpooelqttk");
        r.add("ejfeswctcdbrfnqy");
        r.add("sfduuipjzhhkvtiv");
        r.add("qacecpatcxoibelsaad");
        r.add("hjnirpgylrvicvn");
        r.add("shrnzqokjsmtkcc");
        r.add("rlmeprpzlifivjpdf");
        r.add("iysxcgoufz");
        r.add("dvlahbxlvr");
        r.add("vpkytxfbeaqcioe");
        r.add("hjnirpgylrvicvn");
        r.add("zxyqmmiqnjnpg");
        r.add("mhakcihhthaajuamlg");
        r.add("hlloonkdmanq");
        r.add("qkhwynrlneksncv");
        r.add("maenrdysbritmbtvyy");
        r.add("iysxcgoufz");
        r.add("qmrsqbaatfzu");
        r.add("qacecpatcxoibelsaad");
        r.add("rlmeprpzlifivjpdf");
        r.add("bkclrgwnzmbut");
        r.add("kowvhbqhmthb");
        r.add("eyrphlbrkw");
        r.add("bkclrgwnzmbut");
        r.add("xungqrwaihorcwb");
        r.add("cnzvvbicdocbfzcvg");
        r.add("cvyebywhzrheav");
        r.add("hqsdgjtpfxwzx");
        r.add("rlmeprpzlifivjpdf");
        r.add("bypmwgpbgmsujnlowj");
        r.add("ejfeswctcdbrfnqy");
        r.add("xzscqzxmcejqjq");
        r.add("hjnirpgylrvicvn");
        r.add("xfsjxooclcycwcn");
        r.add("uuqokimbilegfjrhzu");
        r.add("zxyqmmiqnjnpg");
        r.add("sfduuipjzhhkvtiv");
        r.add("gikbbcuucfceho");
        r.add("sgdpknswxysln");
        r.add("xujqjgidmzuilic");
        r.add("nddrscobfrojtwew");
        r.add("fswnwcgwwzazfbw");
        r.add("zrovgoudbnwrougxqz");
        r.add("qfvwoqfsoidz");
        r.add("iufqqsymxpsopnwuyh");
        r.add("pinxwmmeifueviczi");
        r.add("mhakcihhthaajuamlg");
        r.add("xungqrwaihorcwb");
        return r;
    }

    List<Integer> output9() {
        return List.of(
                8,
                10,
                10,
                12,
                10,
                10,
                12,
                10,
                14,
                6,
                9,
                6,
                7,
                4,
                15,
                8,
                7,
                16,
                9,
                7,
                10,
                14,
                10,
                8,
                9,
                8,
                11,
                9,
                16,
                8,
                10,
                15,
                9,
                8,
                8,
                10,
                17,
                7,
                5,
                8,
                12,
                6,
                10,
                10,
                11,
                10,
                12,
                13,
                12,
                7,
                8,
                12,
                11,
                12,
                8,
                16,
                12,
                15,
                14,
                7,
                12,
                12,
                10,
                7,
                6,
                7,
                10,
                11,
                5,
                5,
                10,
                16,
                7,
                8,
                8,
                8,
                3,
                9,
                8,
                8,
                6,
                9,
                10,
                6,
                12,
                9,
                13,
                8,
                9,
                12,
                5,
                8,
                11,
                10,
                6,
                12,
                7,
                10,
                8,
                9,
                13,
                10,
                14,
                5,
                8,
                17,
                8,
                12,
                15,
                9,
                12,
                9,
                11,
                8,
                9,
                10,
                5,
                16,
                8,
                11,
                6,
                7,
                11,
                9,
                9,
                9,
                10,
                5,
                4,
                13,
                12,
                10,
                17,
                13,
                11,
                16,
                8,
                9,
                5,
                12,
                9,
                10,
                4,
                12,
                9,
                15,
                9,
                10,
                8,
                11,
                8,
                5,
                9,
                9,
                14,
                10,
                4,
                12,
                7,
                12,
                15,
                16,
                9,
                7,
                3,
                10,
                3,
                7,
                8,
                10,
                12,
                8,
                10,
                15,
                8,
                11,
                5,
                8,
                11,
                11,
                6,
                12,
                12,
                5,
                11,
                11,
                13,
                9,
                7,
                10,
                7,
                16,
                12,
                12,
                5,
                8,
                11,
                9,
                12,
                12,
                6,
                12,
                12,
                16,
                7,
                7,
                9,
                9,
                17,
                11,
                5,
                5,
                9,
                10,
                8,
                7,
                15,
                8,
                9,
                7,
                9,
                10,
                9,
                9,
                15,
                7,
                5,
                12,
                13,
                12,
                10,
                11,
                9,
                11,
                8,
                8,
                4,
                7,
                15,
                8,
                10,
                6,
                6,
                12,
                11,
                11,
                9,
                15,
                8,
                5,
                10,
                12,
                5,
                12,
                11,
                14,
                8,
                8,
                10,
                15,
                8,
                8,
                6,
                15,
                8,
                14,
                8,
                13,
                14,
                12,
                9,
                11,
                13,
                6,
                9,
                10,
                5,
                7,
                11,
                5,
                16,
                15,
                12,
                7,
                14,
                10,
                14,
                11,
                14,
                12,
                10,
                12,
                11,
                9,
                9,
                9,
                9,
                12,
                9,
                10,
                9,
                14,
                10,
                17,
                5,
                8,
                9,
                12,
                10,
                10,
                9,
                9,
                8,
                16,
                10,
                14,
                11,
                5,
                13,
                8,
                11,
                13,
                7,
                15,
                9,
                14,
                9,
                7,
                6,
                5,
                8,
                9,
                4,
                7,
                11,
                8,
                6,
                6,
                8,
                12,
                16,
                9,
                8,
                7,
                9,
                15,
                10,
                9,
                10,
                10,
                12,
                7,
                11,
                12,
                9,
                9,
                10,
                12,
                12,
                12,
                8,
                5,
                13,
                10,
                9,
                14,
                16,
                7,
                14,
                9,
                8,
                12,
                13,
                7,
                14,
                10,
                10,
                12,
                16,
                17,
                16,
                14,
                9,
                17,
                10,
                10,
                10,
                11,
                7,
                16,
                9,
                8,
                4,
                7,
                11,
                10,
                9,
                8,
                7,
                7,
                6,
                8,
                13,
                10,
                11,
                15,
                12,
                13,
                15,
                8,
                8,
                15,
                6,
                12,
                11,
                10,
                11,
                6,
                10,
                12,
                11,
                10,
                8,
                15,
                17,
                16,
                14,
                7,
                10,
                10,
                8,
                8,
                10,
                7,
                14,
                8,
                8,
                15,
                10,
                12,
                13,
                9,
                14,
                6,
                3,
                5,
                15,
                13,
                11,
                8,
                8,
                12,
                12,
                13,
                10,
                5,
                4,
                9,
                9,
                10,
                12,
                10,
                12,
                14,
                9,
                9,
                16,
                17,
                5,
                12,
                8,
                15,
                8,
                8,
                9,
                12,
                13,
                3,
                12,
                10,
                10,
                10,
                10,
                12,
                9,
                9,
                7,
                15,
                9,
                6,
                12,
                11,
                8,
                13,
                12,
                8,
                13,
                7,
                10,
                9,
                11,
                12,
                10,
                10,
                8,
                3,
                14,
                11,
                10,
                8,
                9,
                12,
                12,
                8,
                8,
                6,
                13,
                11,
                8,
                9,
                11,
                13,
                15,
                9,
                16,
                16,
                9,
                10,
                11,
                7,
                7,
                14,
                12,
                12,
                4,
                7,
                9,
                9,
                12,
                14,
                8,
                6,
                6,
                5,
                7,
                12,
                7,
                5,
                9,
                8,
                12,
                16,
                12,
                9,
                8,
                13,
                11,
                10,
                17,
                7,
                6,
                10,
                9,
                9,
                12,
                10,
                12,
                9,
                10,
                8,
                9,
                12,
                11,
                4,
                9,
                11,
                12,
                9,
                10,
                13,
                7,
                12,
                15,
                9,
                9,
                7,
                9,
                13,
                7,
                9,
                7,
                6,
                17,
                9,
                6,
                11,
                4,
                3,
                9,
                7,
                12,
                8,
                8,
                11,
                12,
                9,
                9,
                10,
                10,
                9,
                8,
                7,
                12,
                7,
                11,
                11,
                14,
                8,
                12,
                15,
                8,
                11,
                7,
                15,
                9,
                12,
                10,
                7,
                7,
                7,
                14,
                3,
                15,
                14,
                8,
                12,
                11,
                11,
                8,
                10,
                10,
                12,
                10,
                9,
                11,
                8,
                4,
                12,
                10,
                8,
                6,
                10,
                12,
                9,
                17,
                13,
                17,
                7,
                15,
                7,
                11,
                11,
                11,
                11,
                15,
                13,
                7,
                12,
                14,
                14,
                8,
                8,
                15,
                8,
                8,
                5,
                11,
                12,
                14,
                7,
                6,
                11,
                11,
                14,
                16,
                4,
                7,
                12,
                7,
                13,
                8,
                14,
                10,
                11,
                8,
                4,
                8,
                12,
                7,
                11,
                5,
                9,
                9,
                10,
                10,
                7,
                8,
                11,
                11,
                7,
                10,
                14,
                9,
                10,
                7,
                13,
                11,
                10,
                13,
                12,
                10,
                8,
                6,
                13,
                8,
                5,
                8,
                11,
                10,
                11,
                11,
                8,
                14,
                7,
                7,
                6,
                12,
                16,
                9,
                9,
                5,
                5,
                12,
                15,
                9,
                8,
                12,
                8,
                6,
                8,
                10,
                11,
                15,
                10,
                11,
                12,
                7,
                14,
                7,
                8,
                11,
                11,
                9,
                11,
                12,
                5,
                11,
                9,
                7,
                17,
                12,
                12,
                16,
                16,
                15,
                13,
                10,
                15,
                11,
                13,
                6,
                13,
                10,
                14,
                13,
                7,
                14,
                7,
                8,
                12,
                11,
                15,
                7,
                10,
                13,
                9,
                8,
                3,
                16,
                12,
                13,
                13,
                14,
                9,
                10,
                7,
                13,
                7,
                3,
                7,
                10,
                10,
                11,
                8,
                16,
                11,
                11,
                8,
                11,
                12,
                8,
                5,
                7,
                11,
                10,
                9,
                7,
                14,
                11,
                11,
                5,
                12,
                11,
                16,
                10,
                13,
                7,
                11,
                11,
                8,
                10,
                9,
                6,
                5,
                12,
                13,
                10,
                12,
                11,
                7,
                16,
                16,
                5,
                6,
                5,
                9,
                8,
                4,
                7,
                10,
                10,
                10,
                15,
                10,
                10,
                10,
                8,
                7,
                11,
                11,
                8,
                14,
                10,
                12,
                16,
                9,
                8,
                9,
                12,
                13,
                8,
                5,
                10,
                15,
                5,
                9,
                14,
                5,
                11,
                12,
                10,
                9,
                12,
                10,
                11,
                11,
                5,
                14,
                14,
                8,
                16,
                17,
                9,
                15,
                11,
                9,
                7,
                10,
                11,
                9,
                16,
                10,
                10,
                16,
                16,
                10,
                14,
                7,
                17,
                15,
                8,
                14,
                5,
                16,
                9,
                12,
                14,
                12,
                12,
                10,
                7,
                9,
                12,
                8,
                8,
                8,
                12,
                9,
                11,
                12,
                13,
                10,
                8,
                9,
                3,
                6,
                13,
                9,
                11,
                8,
                5,
                8,
                12,
                8,
                12,
                10,
                10,
                10,
                7,
                7,
                16,
                13,
                10,
                5,
                16,
                13,
                10,
                11,
                7,
                9,
                10,
                7,
                8,
                11,
                17,
                8,
                5,
                12,
                13,
                13,
                7,
                12,
                8,
                9,
                10,
                15,
                12,
                5,
                12,
                3,
                13,
                8,
                8,
                7,
                9,
                10,
                8,
                9,
                16,
                5);
    }

    List<String> input10_1() {
        List<String> r = new ArrayList<>(4);
        r.add("aba");
        r.add("baba");
        r.add("aba");
        r.add("xzxb");
        return r;
    }

    List<String> input10_2() {
        List<String> r = new ArrayList<>(3);
        r.add("aba");
        r.add("xzxb");
        r.add("ab");
        return r;
    }

    List<String> input11_1() {
        List<String> r = new ArrayList<>(3);
        r.add("def");
        r.add("de");
        r.add("fgh");
        return r;
    }

    List<String> input11_2() {
        List<String> r = new ArrayList<>(3);
        r.add("de");
        r.add("lmn");
        r.add("fgh");
        return r;
    }

    List<String> input12_1() {
        List<String> r = new ArrayList<>(13);
        r.add("abcde");
        r.add("sdaklfj");
        r.add("asdjf");
        r.add("na");
        r.add("basdn");
        r.add("sdaklfj");
        r.add("asdjf");
        r.add("na");
        r.add("asdjf");
        r.add("na");
        r.add("basdn");
        r.add("sdaklfj");
        r.add("asdjf");
        return r;
    }

    List<String> input12_2() {
        List<String> r = new ArrayList<>(5);
        r.add("abcde");
        r.add("sdaklfj");
        r.add("asdjf");
        r.add("na");
        r.add("basdn");
        return r;
    }

}
